/*
 * WireGuard hub setup-script generator.
 *
 * Pure string templating: given a validated config (entered on the WireGuard Hub
 * webUI page) it returns a single self-contained bash script the user runs ONCE
 * on a fresh VPS. The script stands up the WireGuard "rendezvous" server (the
 * public hub both the drone and the ground station dial out to — required
 * because the drone is behind CGNAT and cannot accept inbound connections), then
 * prints ready-to-use Pi and laptop configs.
 *
 * No private keys are generated here — the script generates all three keypairs on
 * the VPS, so secrets never touch the companion computer. The webUI only ships
 * the script *text*. See docs/WIREGUARD-HUB.md.
 */

interface HubConfig {
  vpsIp: string // VPS public IPv4 (A-record target; printed for reference)
  domain: string // FQDN used as the Endpoint host in the Pi/laptop configs
  port: number // WireGuard UDP listen port
  subnet: string // VPN subnet, e.g. '10.13.13.0/24' (hub .1, pi .2, laptop .3)
  sshPort: number // existing SSH port to keep open in the firewall
}

function generateScript (cfg: HubConfig): string {
  // Derive the host addresses from the subnet's first three octets. A /24 is
  // assumed for the addresses (ample for a hub + drone + ground station).
  const base = cfg.subnet.split('/')[0].split('.').slice(0, 3).join('.')
  const hubAddr = base + '.1'
  const piAddr = base + '.2'
  const laptopAddr = base + '.3'
  const cidr = base + '.0/24'

  // Everything below is bash. JS interpolation (${...}) bakes the validated
  // config in as literals; bash uses $VAR / $(...) (never ${...}) so it survives
  // this template literal untouched.
  return `#!/usr/bin/env bash
#
# WireGuard hub setup — generated by the Rpanion-server WireGuard Hub page.
# Run ONCE on a fresh VPS as root:   sudo bash setup-wireguard-hub.sh
#
# Before running: create a DNS A record  ${cfg.domain}  ->  ${cfg.vpsIp}
# and make sure your VPS provider's firewall/security group allows inbound
# UDP ${cfg.port}.
#
# Idempotent: safe to re-run (existing keys are reused).
set -euo pipefail

# ---- configuration (from the webUI) ----------------------------------------
WG_PORT=${cfg.port}
SSH_PORT=${cfg.sshPort}
ENDPOINT=${cfg.domain}
HUB_ADDR=${hubAddr}
PI_ADDR=${piAddr}
LAPTOP_ADDR=${laptopAddr}
VPN_CIDR=${cidr}
WG_DIR=/etc/wireguard
# ----------------------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run this script as root (sudo bash $0)" >&2
  exit 1
fi

echo "==> Installing WireGuard..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y wireguard wireguard-tools iptables ufw

echo "==> Enabling IP forwarding..."
echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-wireguard-hub.conf
sysctl --system >/dev/null

# Auto-detect the public-facing interface for NAT (the route to the internet).
WAN_IF=$(ip -o -4 route show to default | awk '{print $5; exit}')
echo "==> Public interface detected: $WAN_IF"

echo "==> Generating keys (reused if they already exist)..."
mkdir -p "$WG_DIR/clients"
umask 077
cd "$WG_DIR"
for name in hub pi laptop; do
  if [ ! -f "$name.key" ]; then
    wg genkey | tee "$name.key" | wg pubkey > "$name.pub"
  fi
done

echo "==> Writing hub config ($WG_DIR/wg0.conf)..."
cat > "$WG_DIR/wg0.conf" <<EOF
[Interface]
Address = $HUB_ADDR/24
ListenPort = $WG_PORT
PrivateKey = $(cat hub.key)
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o $WAN_IF -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o $WAN_IF -j MASQUERADE

[Peer]
# Pi / drone
PublicKey = $(cat pi.pub)
AllowedIPs = $PI_ADDR/32

[Peer]
# Laptop / ground station
PublicKey = $(cat laptop.pub)
AllowedIPs = $LAPTOP_ADDR/32
EOF
chmod 600 "$WG_DIR/wg0.conf"

echo "==> Configuring firewall (keeping SSH on $SSH_PORT, opening UDP $WG_PORT)..."
ufw allow "$SSH_PORT"/tcp
ufw allow "$WG_PORT"/udp
ufw --force enable

echo "==> Starting WireGuard (enabled on boot)..."
systemctl enable wg-quick@wg0
systemctl restart wg-quick@wg0

# ---- emit the client configs -----------------------------------------------
cat > "$WG_DIR/clients/pi.conf" <<EOF
[Interface]
PrivateKey = $(cat pi.key)
Address = $PI_ADDR/24

[Peer]
PublicKey = $(cat hub.pub)
Endpoint = $ENDPOINT:$WG_PORT
AllowedIPs = $VPN_CIDR
PersistentKeepalive = 25
EOF

cat > "$WG_DIR/clients/laptop.conf" <<EOF
[Interface]
PrivateKey = $(cat laptop.key)
Address = $LAPTOP_ADDR/24

[Peer]
PublicKey = $(cat hub.pub)
Endpoint = $ENDPOINT:$WG_PORT
AllowedIPs = $VPN_CIDR
PersistentKeepalive = 25
EOF
chmod 600 "$WG_DIR/clients/"*.conf

# Make the configs easy to pull off this VPS. The originals are root-owned 600;
# if the script was run via sudo, drop copies the login user owns so they can
# scp them without root SSH login. Otherwise point scp at the root-owned paths.
SCP_USER=root
PI_PATH="$WG_DIR/clients/pi.conf"
LAPTOP_PATH="$WG_DIR/clients/laptop.conf"
if [ -n "\${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
  USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
  install -m 600 -o "$SUDO_USER" "$WG_DIR/clients/pi.conf" "$USER_HOME/pi.conf"
  install -m 600 -o "$SUDO_USER" "$WG_DIR/clients/laptop.conf" "$USER_HOME/laptop.conf"
  SCP_USER="$SUDO_USER"
  PI_PATH="$USER_HOME/pi.conf"
  LAPTOP_PATH="$USER_HOME/laptop.conf"
fi

echo ""
echo "============================================================"
echo " DONE. WireGuard hub is running on UDP $WG_PORT."
echo "============================================================"
echo ""
echo " 1) On the drone: open the Rpanion WireGuard (VPN) page and"
echo "    upload this file as the profile, then Activate it:"
echo ""
echo "------------------------- pi.conf --------------------------"
cat "$WG_DIR/clients/pi.conf"
echo "------------------------------------------------------------"
echo ""
echo " 2) On the laptop: import this into your WireGuard client"
echo "    and Activate it. Mission Planner then connects to the"
echo "    drone at $PI_ADDR."
echo ""
echo "----------------------- laptop.conf ------------------------"
cat "$WG_DIR/clients/laptop.conf"
echo "------------------------------------------------------------"
echo ""
echo " Prefer files over copy-paste? Run these on your LAPTOP (not"
echo " here) to pull the configs off this VPS:"
echo ""
echo "   scp $SCP_USER@${cfg.vpsIp}:$PI_PATH ."
echo "   scp $SCP_USER@${cfg.vpsIp}:$LAPTOP_PATH ."
echo ""
echo " Reminder: DNS A record  $ENDPOINT -> ${cfg.vpsIp}  must exist,"
echo " and your VPS firewall must allow inbound UDP $WG_PORT."
`
}

export = { generateScript }
